### ISSUE TITLE
'Segmentation fault' error with xvidcore 1.3.5

### ISSUE THREAD

**Issue by gaurii386** [soyokaze/SCXvid-standalone#2]
When I running command `ffmpeg -i "somefile.mkv" -f yuv4mpegpipe -vf scale=640:360 -pix_fmt yuv420p -vsync drop -loglevel quiet - | scxvid "output.log"` in Mageia 7 with xvidcore 1.3.5, I always get 'Segmentation fault' error. If I replace the xvidcore package to 1.3.4 from Mageia 6, then all work fine.

**Comment by soyokaze** [comment]
Hello.

I've done some investigating on your issue and found out that it's caused by a known bug in xvidcore 1.3.5 when it's built by binutils version 2.31 or later.

Details here: http://list.xvid.org/pipermail/xvid-devel/2019-January/006449.html

A patch suitable for RPM packages can be found here: https://github.com/rpmfusion/xvidcore/blob/master/xvidcore-check_cpu_features-crash.patch

I suggest you take this issue to Mageia maintainers and urge them to release an updated package.
For now, you'll either have to stick with xvidcore 1.3.4 or you can try to build patched xvidcore 1.3.5 yourself.

**Comment by gaurii386** [comment]
Hello.
Thank you for clarification the issue. I have created a bug in Magea Bugzilla. It should be fixed soon.
